[package]
name = "rustp2p"
version = "0.1.2"
authors = ["Dan Rammer <hamersaw@gmail.com>"]
build = "build.rs"

[build-dependencies]
capnpc = "0.5.0"

[dependencies]
argparse = "0.2.1"
capnp = "0.5.0"
